/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plantsvszombies;

import Clases.Campo;
import java.awt.List;
import java.net.URL;
import java.util.Iterator;
import java.util.LinkedList;
import javax.swing.ImageIcon;

/**
 *
 * @author Adrian
 */
public class fJugadores extends javax.swing.JFrame {

    private String tipo;
    public LinkedList<Campo> jplanta = new LinkedList<Campo>();
    public LinkedList<Campo> jzombie = new LinkedList<Campo>();
    public fJugadores(String tipo) {
        this.tipo = tipo;
        initComponents();
        bFinalizar.setOpaque(false);
        bFinalizar.setContentAreaFilled(false);
        bFinalizar.setBorderPainted(true);
        URL url = getClass().getResource("/Imagenes/icon.png");
        ImageIcon icono = new ImageIcon(url);
        setIconImage(icono.getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bFinalizar = new javax.swing.JButton();
        tfNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfExtra = new javax.swing.JTextField();
        bExtra = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/finalizar.png"))); // NOI18N
        bFinalizar.setContentAreaFilled(false);
        bFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(bFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 150, 30));
        getContentPane().add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 128, -1));

        jLabel2.setText("Cantidad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));
        getContentPane().add(tfCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 95, -1));

        jLabel3.setText("Campo Extra");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));
        getContentPane().add(tfExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 128, -1));

        bExtra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
        bExtra.setContentAreaFilled(false);
        bExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExtraActionPerformed(evt);
            }
        });
        getContentPane().add(bExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 30, 30));

        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(386, 408));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExtraActionPerformed
        Campo campo = new Campo("extra",tfExtra.getText());
        if(tipo.equals("plantas"))
        {
            jplanta.add(campo);
        }
        else
        {
            jzombie.add(campo);
        }
    }//GEN-LAST:event_bExtraActionPerformed

    private void bFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFinalizarActionPerformed
        // TODO add your handling code here:
        Campo campo1 = new Campo("nombre",tfNombre.getText());
        try
        {
            int x = Integer.parseInt(tfCantidad.getText());
            Campo campo2 = new Campo("cantidad",tfCantidad.getText());
            if(tipo.equals("plantas"))
            {
                jplanta.add(campo1);
                jplanta.add(campo2);
                fPrincipal.Jugadores.add(jplanta);
            }
            else
            {
                jzombie.add(campo1);
                jzombie.add(campo2);
                fPrincipal.Jugadores.add(jzombie);
            }
            /*
            RECORRE LA LISTA DE JUGADORES
            */
            Iterator i = fPrincipal.Jugadores.iterator();
            while(i.hasNext())
            {
                LinkedList<LinkedList> temp = (LinkedList<LinkedList>) i.next();
                Iterator it = temp.iterator();
                System.out.println("lista");
                while(it.hasNext())
                {
                    /*
                    RECORRE LA LISTA DEL JUGADOR PLANTA
                    */
                    Campo t = null;
                    if(tipo.equals("plantas"))
                    {
                        t = (Campo) it.next();
                        System.out.println("plantas");
                        System.out.println(t.getTipo() + ": " + t.getAtributo());   
                    }
                    /*
                    RECORRE LA LISTA DEL JUGADOR ZOMBIE
                    */
                    else
                    {
                        t = (Campo) it.next();
                        System.out.println("zombies");
                        System.out.println(t.getTipo() + ": " + t.getAtributo());
                    }
                }
            }
        }
        catch(Exception e)
        {
            System.out.println("La cantidad no es un numero");
        }
    }//GEN-LAST:event_bFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExtra;
    private javax.swing.JButton bFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tfCantidad;
    private javax.swing.JTextField tfExtra;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
